namespace SchedulingApp.Views;
using SchedulingApp.Models;
public partial class MySchedulePage : ContentPage
{
	/*
	 * Author: Alex Sorichetti
	 * Date: Nov 19, 2025
	 * Desc: Backend for the page displaying user's scheduled shifts
	 */
	public MySchedulePage()
	{
		InitializeComponent();
		LoadMySchedule();
	}

	//Loads user's scheduled shifts
	private void LoadMySchedule()
	{
        //Sample of upcoming shifts -- note, sample data generated by Claude AI
        var upcomingShifts = new List<Shift>
        {
            new Shift
            {
                Id = 1,
                Title = "Food Bank - Sorting",
                StartTime = DateTime.Now.AddDays(2),
                EndTime = DateTime.Now.AddDays(2).AddHours(3),
                Location = "Community Center",
                OrganizationName = "City Food Bank"
            },
            new Shift
            {
                Id = 2,
                Title = "Park Cleanup",
                StartTime = DateTime.Now.AddDays(5),
                EndTime = DateTime.Now.AddDays(5).AddHours(2),
                Location = "Central Park",
                OrganizationName = "Green City Initiative"
            },
            new Shift
            {
                Id = 3,
                Title = "Tutoring Session",
                StartTime = DateTime.Now.AddDays(7),
                EndTime = DateTime.Now.AddDays(7).AddHours(1.5),
                Location = "Library - Room 3",
                OrganizationName = "Youth Education Program"
            }
        };

        // Sample past shifts
        var pastShifts = new List<Shift>
        {
            new Shift
            {
                Id = 4,
                Title = "Animal Shelter - Dog Walking",
                StartTime = DateTime.Now.AddDays(-3),
                EndTime = DateTime.Now.AddDays(-3).AddHours(2),
                Location = "Happy Paws",
                OrganizationName = "Happy Paws Animal Shelter"
            },
            new Shift
            {
                Id = 5,
                Title = "Senior Center - Game Night",
                StartTime = DateTime.Now.AddDays(-10),
                EndTime = DateTime.Now.AddDays(-10).AddHours(3),
                Location = "Golden Years Center",
                OrganizationName = "Elder Care Services"
            }
        };

        // Update summary
        UpcomingShiftsLabel.Text = upcomingShifts.Count.ToString();
        var totalHours = upcomingShifts.Sum(s => (s.EndTime - s.StartTime).TotalHours);
        TotalHoursLabel.Text = totalHours.ToString("F1");

        // Set data sources
        UpcomingShiftsCollection.ItemsSource = upcomingShifts;
        PastShiftsCollection.ItemsSource = pastShifts;
    }

    //Navigates to browse shifts page
    private async void OnBrowseShiftsClicked(object sender, EventArgs e)
    {
        await Shell.Current.GoToAsync("//ShiftsPage");
    }
}